<a href="https://colab.research.google.com/github/haseeb-505/Python-Project-For-Data-Science/blob/main/assignment_1_question2_Housing_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**a): Write a function in Python that takes two vectors as input (weight and feature vector) and returns the linear regression prediction for that input.**

In [ ]:
!nvidia-smi

Thu Oct 26 05:29:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import math

In [ ]:
lr=LinearRegression()

In [ ]:
def linear_regression_computer(x,w):
    """w: w is weight vector with values equal to 1. it is here user defined.. it can be calculated.\\
    x: x is feature vector;\\
    b: bias vector, and it can be added by user"""

#     b=np.array(x.shape) # since b and w are to be used in coming cells too, so we will define them globally
#     w=np.one(x.shape, float)
#     for i in range(len(x)):


    prediction=np.dot(x,w)
    return prediction



**b): Write a function in Python that takes a vector of predictions and a vector of actual values as
input and returns the Mean Squared Error.**

In [ ]:
# from sklearn.metrics import mean_squared_error as mse


def mse_calculator(y_true, y_pred):
    """y_true: ture values\\
    y_pred: predicted values"""
    return sum((y_true-y_pred)**2)/len(y_true)

# y_test=[[2,4]]
# y_pred=lr.predict(w_test)

# mse_calculator(y_true=y_test, y_pred=y_pred)


**c): Write a function in Python that takes a vector of predictions and training data as input and
returns the Gradient of Mean Squared Error.**

In [ ]:
def mse_gradient(x,y,w):
    """
    x: as of now, x is X_train.
    y: y is y_train
    """
    w_der=[]

    mse_grad=0

    for j in range(x.shape[0]):
#             mse=mse+(np.dot(x.iloc[j],w)-y.iloc[j])**2

        mse_grad=mse_grad+2*(np.dot((np.dot(x.iloc[j],w)-y.iloc[j]),x.iloc[j]))

    mse_grad/len(y)
    w_der.append(mse_grad)

    return w_der

**d): Write a function in Python that implements the gradient descent algorithm. The function
should take a weight vector, gradient of loss and a stopping criterion as input and return the
optimized weight vector.**

In [ ]:


def grad_descent(x, y, initial_weight, step=0.1, iteration=10000):
    current_w=initial_weight
    print(current_w)

    w_update=[]
    loss=[]


    for i in range(iteration):
#         print(i)

        prediction=linear_regression_computer(X_train,w)
        mse=mse_calculator(y_train, prediction)
        w_der=mse_gradient(x,y,current_w)[0]

#         print(w_der)

#         print(current_w)

        current_w=current_w-(step*w_der)
#         print(current_w)
        w_update.append(current_w)
        loss.append(mse)


    return current_w

**e):  Use the functions created in the previous parts to apply linear regression on the California
Housing Dataset. You can You can find details about this dataset at the following link:
https://developers.google.com/machine-learning/crash-course/california-housing-datadescription**

In [ ]:
url="https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv"

In [ ]:
data=pd.read_csv(url)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


**There are no null/nan values in  the data. Moreover, all the data is of float type, i.e., continuous data. It is, in other terms, ready to use for linear regression.**

In [ ]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

**Finding the correlation between the data and the median_house_value**

In [ ]:
data.corrwith(data["median_house_value"])

longitude            -0.044982
latitude             -0.144917
housing_median_age    0.106758
total_rooms           0.130991
total_bedrooms        0.045783
population           -0.027850
households            0.061031
median_income         0.691871
median_house_value    1.000000
dtype: float64

In [ ]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

**This shows that median_house_value is mostly depending on median_income.**

### Let's split the data into train, test set

In [ ]:
### Scaling data

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
sc.fit_transform(data)

array([[ 2.619365  , -0.67152023, -1.07967114, ..., -0.07599796,
        -1.25254316, -1.21055773],
       [ 2.53956878, -0.57326437, -0.76187201, ..., -0.09940441,
        -1.08148298, -1.09674535],
       [ 2.4946834 , -0.90546278, -0.92077158, ..., -0.99925206,
        -1.17010515, -1.04846131],
       ...,
       [-2.36291168,  2.90780067, -0.92077158, ..., -0.11760942,
        -0.44666313, -0.89412482],
       [-2.36291168,  2.88908527, -0.76187201, ..., -0.06039367,
        -0.99778717, -1.04759909],
       [-2.387848  ,  2.29955006,  1.85997083, ..., -0.60134255,
        -0.45536288, -0.97172417]])

In [ ]:
data=pd.DataFrame(sc.fit_transform(data), columns=data.columns)

In [ ]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   2.619365 -0.671520           -1.079671     1.361695        1.764204   
1   2.539569 -0.573264           -0.761872     2.296608        3.230441   
2   2.494683 -0.905463           -0.920772    -0.882462       -0.866956   
3   2.489696 -0.928857           -1.159121    -0.524186       -0.480230   
4   2.489696 -0.961609           -0.682422    -0.545747       -0.506328   

   population  households  median_income  median_house_value  
0   -0.361184   -0.075998      -1.252543           -1.210558  
1   -0.261865   -0.099404      -1.081483           -1.096745  
2   -0.955354   -0.999252      -1.170105           -1.048461  
3   -0.796793   -0.715774      -0.362600           -1.154514  
4   -0.701830   -0.622148      -1.026454           -1.222629

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(data.drop(["median_house_value"],axis=1), data["median_house_value"], test_size=0.2, random_state=42)

In [ ]:
X_train

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
4679    0.744154 -0.849317           -0.523523     0.030890       -0.444642   
2512    0.963593 -0.994361           -1.318020     0.447426       -0.008092   
993     1.232906 -1.429494           -0.920772    -1.009075       -1.082858   
1327    1.197995 -1.317202            0.429875    -0.169121       -0.390073   
4630    0.744154 -0.680878            0.588774    -0.104898       -0.344995   
...          ...       ...                 ...          ...             ...   
11284  -0.781949  0.989472           -0.602972    -0.122788       -0.152818   
11964  -0.906631  1.401211            0.986023    -0.857690       -0.938133   
5390    0.704256 -0.802528            0.747674    -0.799430       -0.793407   
860     1.242880 -1.434173           -1.556370     0.460729        0.843654   
15795  -1.420319  0.994151            1.859971    -0.087924        0.198320   

       population  households  median_income  
4679    -0.108531   -0.346472       2.440711  
2512     0.066584   -0.023984       1.738756  
993     -0.934445   -1.077274       0.662555  
1327    -0.355957   -0.317865      -0.129175  
4630    -0.186941   -0.229440       0.869043  
...           ...         ...            ...  
11284   -0.221789   -0.156620      -0.147779  
11964   -0.935316   -0.913428      -0.168271  
5390    -0.583344   -0.762587      -0.481777  
860      1.623449    0.881065      -0.411078  
15795    0.437722    0.124257      -0.782599  

[13600 rows x 8 columns]

In [ ]:
# since b and w are to be used in coming cells too, so we will define them globally
w=np.random.random(X_train.shape[1])

In [ ]:
X_train.shape

(13600, 8)

In [ ]:
X_train

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
4679    0.744154 -0.849317           -0.523523     0.030890       -0.444642   
2512    0.963593 -0.994361           -1.318020     0.447426       -0.008092   
993     1.232906 -1.429494           -0.920772    -1.009075       -1.082858   
1327    1.197995 -1.317202            0.429875    -0.169121       -0.390073   
4630    0.744154 -0.680878            0.588774    -0.104898       -0.344995   
...          ...       ...                 ...          ...             ...   
11284  -0.781949  0.989472           -0.602972    -0.122788       -0.152818   
11964  -0.906631  1.401211            0.986023    -0.857690       -0.938133   
5390    0.704256 -0.802528            0.747674    -0.799430       -0.793407   
860     1.242880 -1.434173           -1.556370     0.460729        0.843654   
15795  -1.420319  0.994151            1.859971    -0.087924        0.198320   

       population  households  median_income  
4679    -0.108531   -0.346472       2.440711  
2512     0.066584   -0.023984       1.738756  
993     -0.934445   -1.077274       0.662555  
1327    -0.355957   -0.317865      -0.129175  
4630    -0.186941   -0.229440       0.869043  
...           ...         ...            ...  
11284   -0.221789   -0.156620      -0.147779  
11964   -0.935316   -0.913428      -0.168271  
5390    -0.583344   -0.762587      -0.481777  
860      1.623449    0.881065      -0.411078  
15795    0.437722    0.124257      -0.782599  

[13600 rows x 8 columns]

from matplotlib import pyplot as plt
X_train['longitude'].plot(kind='hist', bins=20, title='longitude')
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
X_train['latitude'].plot(kind='hist', bins=20, title='latitude')
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
X_train['housing_median_age'].plot(kind='hist', bins=20, title='housing_median_age')
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
X_train['total_rooms'].plot(kind='hist', bins=20, title='total_rooms')
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
plt.figure(figsize=(6, 6))
X_train.plot(kind='scatter', x='longitude', y='latitude', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
plt.figure(figsize=(6, 6))
X_train.plot(kind='scatter', x='latitude', y='housing_median_age', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
plt.figure(figsize=(6, 6))
X_train.plot(kind='scatter', x='housing_median_age', y='total_rooms', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
plt.figure(figsize=(6, 6))
X_train.plot(kind='scatter', x='total_rooms', y='total_bedrooms', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
X_train['longitude'].plot(kind='line', figsize=(8, 4), title='longitude')
plt.gca().spines[['top', 'right']].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
X_train['latitude'].plot(kind='line', figsize=(8, 4), title='latitude')
plt.gca().spines[['top', 'right']].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
X_train['housing_median_age'].plot(kind='line', figsize=(8, 4), title='housing_median_age')
plt.gca().spines[['top', 'right']].set_visible(False)
plt.tight_layout()

from matplotlib import pyplot as plt
X_train['total_rooms'].plot(kind='line', figsize=(8, 4), title='total_rooms')
plt.gca().spines[['top', 'right']].set_visible(False)
plt.tight_layout()

#### LinearRegression_Prediction

In [ ]:

prediction=linear_regression_computer(X_train, w)
prediction

array([-0.02967318,  0.3012633 , -2.22584567, ..., -1.25153408,
        0.7179601 ,  0.61438168])

In [ ]:
y_test

10941   -0.556999
5250     2.523704
10292   -1.254531
2266    -0.383694
6398    -1.006213
           ...   
4706     0.035343
8404     2.523704
11114   -0.386280
7877     1.322630
6188    -0.601834
Name: median_house_value, Length: 3400, dtype: float64

#### MSE Calculator

In [ ]:
mse_calculator(y_train, prediction)

3.81906427675818

#### Gradient of MSE

In [ ]:
mse_gradient(X_train, y_train, w)[0]

array([  6190.41118535,  -2311.21656674, -10031.67295516,  45197.15408752,
        47017.22336088,  45348.78265058,  46384.01415574,  -9762.68882093])

#### Gradeient Descent

In [ ]:
w

array([0.13594868, 0.01582967, 0.45464937, 0.98014543, 0.67824275,
       0.04849305, 0.29619622, 0.20478028])

In [ ]:
%%time
grad_descent(X_train, y_train, initial_weight=w, iteration=25)

[0.13594868 0.01582967 0.45464937 0.98014543 0.67824275 0.04849305
 0.29619622 0.20478028]
CPU times: user 53 s, sys: 4.56 s, total: 57.6 s
Wall time: 1min 2s


array([-3.07848790e+099,  2.96446014e+099,  8.80139141e+099,
       -1.92175870e+100, -1.95780560e+100, -1.90537308e+100,
       -1.96177808e+100, -1.56510862e+099])

In [ ]:
for i in X_train:
    print(i)


longitude
latitude
housing_median_age
total_rooms
total_bedrooms
population
households
median_income


In [ ]:
X_train[i]

4679     2.440711
2512     1.738756
993      0.662555
1327    -0.129175
4630     0.869043
           ...   
11284   -0.147779
11964   -0.168271
5390    -0.481777
860     -0.411078
15795   -0.782599
Name: median_income, Length: 13600, dtype: float64

In [ ]:
X_train.shape

(13600, 8)

In [ ]:
X_train.iloc[1]

longitude             0.963593
latitude             -0.994361
housing_median_age   -1.318020
total_rooms           0.447426
total_bedrooms       -0.008092
population            0.066584
households           -0.023984
median_income         1.738756
Name: 2512, dtype: float64

In [ ]:
X_train.iloc[0]

longitude             0.744154
latitude             -0.849317
housing_median_age   -0.523523
total_rooms           0.030890
total_bedrooms       -0.444642
population           -0.108531
households           -0.346472
median_income         2.440711
Name: 4679, dtype: float64

In [ ]:
X_train.iloc[0].shape

(8,)

In [ ]:
X_train.iloc[0][1]

-0.8493165671352897

In [ ]:
X_train.iloc[0][0]

0.7441537602546566

In [65]:
def regression_calculator(x,w,b):
    pred=0
    f_wb=[]
    for i in range(x.shape[0]):

        pred=np.dot(x.iloc[i],w) + b

        f_wb.append(pred)

    return f_wb

In [66]:
### Initializing the weight vector
from numpy import random
random.seed(42)
w=np.random.rand(X_train.shape[1])
w

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615])

In [67]:
### setting the value of b, let it be 3
b=3

In [68]:
regression_calculator(X_train, w, b)

[4.114193630700481,
 3.232423810748225,
 1.0212450866149636,
 2.1630978464399675,
 3.6560070123366732,
 2.352077130788538,
 3.2111645298165303,
 2.1578636234060045,
 3.224143407780901,
 2.517206253910639,
 3.1937686137063235,
 2.654217361719936,
 1.8450370849894715,
 2.088325339204723,
 3.3752551969263904,
 1.6048081013535918,
 1.9430068901648787,
 3.8297964128783173,
 3.2729624722645756,
 2.2824371631902487,
 4.2727609444782155,
 2.308277354386579,
 3.825234413151472,
 1.390029793122909,
 3.5583019016653834,
 2.3917350968806383,
 2.5977270052965094,
 1.6341653421913178,
 2.9253502886043004,
 3.4945141615847928,
 2.574646726251354,
 2.721767681686411,
 1.6588814713497937,
 2.8503035840099296,
 2.5434025449328033,
 2.650723051389786,
 6.1507415927778375,
 3.6839938606853346,
 2.503689933496263,
 1.5467594688650483,
 2.960377597861889,
 2.8274192585365983,
 2.3648608993924407,
 3.308194227207022,
 1.4287375948097378,
 2.6970525327993844,
 3.128579643296898,
 5.570017277601691,
 -0.078725

In [94]:
len(regression_calculator(X_train, w, b))

13600

In [95]:
y_train.shape

(13600,)

In [70]:
y_train

4679     1.651134
2512     1.261413
993     -0.589763
1327    -0.267295
4630     1.024304
           ...   
11284   -0.626838
11964   -0.793246
5390    -0.516475
860     -0.557861
15795    0.248310
Name: median_house_value, Length: 13600, dtype: float64

In [71]:
def cost_calculator(x,y,w,b):

    cost=0

    for i in range(x.shape[0]):

        f_wb=np.dot(x.iloc[i],w) + b

#         cost calculator
        cost+=(f_wb-y.iloc[i])**2

#     dividing by number of events, as it is in mean squared error formula
    cost=cost/x.shape[0]

    return cost

In [72]:
cost_calculator(X_train, y_train, w, b)

10.681004938465566

In [73]:
def gradient_calculator(x,y,w,b):

    dw=0
    db=0

    for i in range(x.shape[0]):

        f_wb=np.dot(x.iloc[i],w)+b

#       differential of cost w.r.t w and we will divide the sum later on by x.shape[0]
        dw_i=sum((np.dot(X_train.iloc[i],w)+b-y_train.iloc[i])*X_train.iloc[i])
#       sum of differentials
        dw+=dw_i
#     differential of cost w.r.t bias and we will divide the sum later on by x.shape[0]
        db_i=(f_wb-y.iloc[i])
#     sum of bias differential
        db+=db_i
#     division by x.shape[0]
    dw=dw/x.shape[0]
    db=db/x.shape[0]

    return dw, db


In [74]:
dw,db=gradient_calculator(X_train,y_train,w,b)

In [75]:
dw

2.8651281236850266

In [76]:
db

3.0019051145247495

### updating weights and bias using batch gradient descent

In [77]:
def gradient_updation(x,y,w,b, cost_function=cost_calculator,
                      gradient_function=gradient_calculator,  iterations=100000, alpha=0.1):

    cost_history=[]
    w_history=[]

    for i in range(iterations):
        dw, db=gradient_function(x,y,w,b)
#       updating the parameters
        w=w-alpha*dw

        b=b-alpha*db

#       saving the cost for each iteration
        if i<100000:
            cost=cost_function(x,y,w,b)
            cost_history.append(cost)
        # Print cost every at intervals 20 times or as many iterations if < 20
        if i% math.ceil(iterations/100)==0:
            w_history.append(w)
            print(f"Iteration {i:4}: Cost {float(cost_history[-1]):8.5f}   ")

    return w,b, cost_history, w_history

In [78]:
w=np.array([0,0,0,0,0,0,0,0])
b=0

In [79]:
%%time
w,b,cost_history,w_history = gradient_updation(X_train, y_train, w, b, iterations=50)

Iteration    0: Cost  0.95646   
Iteration    1: Cost  0.94976   
Iteration    2: Cost  0.94856   
Iteration    3: Cost  0.94834   
Iteration    4: Cost  0.94830   
Iteration    5: Cost  0.94829   
Iteration    6: Cost  0.94829   
Iteration    7: Cost  0.94829   
Iteration    8: Cost  0.94829   
Iteration    9: Cost  0.94829   
Iteration   10: Cost  0.94829   
Iteration   11: Cost  0.94829   
Iteration   12: Cost  0.94829   
Iteration   13: Cost  0.94829   
Iteration   14: Cost  0.94829   
Iteration   15: Cost  0.94829   
Iteration   16: Cost  0.94829   
Iteration   17: Cost  0.94829   
Iteration   18: Cost  0.94829   
Iteration   19: Cost  0.94829   
Iteration   20: Cost  0.94829   
Iteration   21: Cost  0.94829   
Iteration   22: Cost  0.94829   
Iteration   23: Cost  0.94829   
Iteration   24: Cost  0.94829   
Iteration   25: Cost  0.94829   
Iteration   26: Cost  0.94829   
Iteration   27: Cost  0.94829   
Iteration   28: Cost  0.94829   
Iteration   29: Cost  0.94829   
Iteration 

In [80]:
w

array([0.0565394, 0.0565394, 0.0565394, 0.0565394, 0.0565394, 0.0565394,
       0.0565394, 0.0565394])

In [81]:
b

-0.005074590564110888

In [82]:
w_history

[array([0.08047219, 0.08047219, 0.08047219, 0.08047219, 0.08047219,
        0.08047219, 0.08047219, 0.08047219]),
 array([0.04640894, 0.04640894, 0.04640894, 0.04640894, 0.04640894,
        0.04640894, 0.04640894, 0.04640894]),
 array([0.06082763, 0.06082763, 0.06082763, 0.06082763, 0.06082763,
        0.06082763, 0.06082763, 0.06082763]),
 array([0.05472431, 0.05472431, 0.05472431, 0.05472431, 0.05472431,
        0.05472431, 0.05472431, 0.05472431]),
 array([0.05730779, 0.05730779, 0.05730779, 0.05730779, 0.05730779,
        0.05730779, 0.05730779, 0.05730779]),
 array([0.05621421, 0.05621421, 0.05621421, 0.05621421, 0.05621421,
        0.05621421, 0.05621421, 0.05621421]),
 array([0.05667711, 0.05667711, 0.05667711, 0.05667711, 0.05667711,
        0.05667711, 0.05667711, 0.05667711]),
 array([0.05648116, 0.05648116, 0.05648116, 0.05648116, 0.05648116,
        0.05648116, 0.05648116, 0.05648116]),
 array([0.0565641, 0.0565641, 0.0565641, 0.0565641, 0.0565641, 0.0565641,
        0.0565

In [83]:
cost_history

[0.9564592026447815,
 0.9497636308292106,
 0.9485614187510496,
 0.9483439656677319,
 0.9483033465516599,
 0.9482947266443749,
 0.948292095199711,
 0.9482907432678123,
 0.9482897878776726,
 0.9482890390380257,
 0.9482884369620587,
 0.9482879500839645,
 0.9482875558566654,
 0.9482872365583573,
 0.9482869779313425,
 0.9482867684442836,
 0.948286598759919,
 0.9482864613156105,
 0.9482863499857236,
 0.9482862598085217,
 0.9482861867649787,
 0.9482861275997111,
 0.9482860796758513,
 0.9482860408575141,
 0.9482860094146651,
 0.948285983945966,
 0.948285963316312,
 0.9482859466062982,
 0.9482859330711797,
 0.9482859221077337,
 0.9482859132273428,
 0.9482859060342299,
 0.9482859002078068,
 0.9482858954884094,
 0.9482858916656899,
 0.9482858885692852,
 0.9482858860612032,
 0.9482858840296529,
 0.9482858823841044,
 0.948285881051204,
 0.9482858799715483,
 0.9482858790970407,
 0.9482858783886844,
 0.948285877814913,
 0.9482858773501593,
 0.9482858769737096,
 0.9482858766687832,
 0.948285876421797,

### Using the updated w and b to make prediction on test data

In [84]:
predicted_value=regression_calculator(X_test, w, b)

In [85]:
predicted_value

[0.13900697871942194,
 0.1857606675423544,
 0.05430501439482406,
 0.18462423561773977,
 -0.07117566577224838,
 -0.10910742833617733,
 -0.19778295588973901,
 -0.25174833711872896,
 -0.050244516250433136,
 0.03206543591993247,
 -0.18023016561216296,
 -0.03437544913567392,
 -0.026897187433815313,
 -0.08708601931337767,
 0.040555415276288774,
 -0.17568175240104883,
 -0.10825792676784708,
 -0.23496197571122066,
 -0.18443309114251968,
 0.10707098099374242,
 -0.2056100234117352,
 -0.2600779848189988,
 -0.052923883000398346,
 0.19953299103770725,
 0.1203847075793757,
 -0.08464958176649606,
 -0.112163231100411,
 -0.08589087358012626,
 -0.13376220254174434,
 -0.27119940669545484,
 -0.082448532132669,
 -0.13197276973466085,
 -0.13837500826513197,
 -0.13844081455122184,
 -0.0651574504823549,
 -0.015371864432245037,
 -0.19469352572752463,
 0.09242776551331203,
 -0.2048450395947871,
 -0.06938196642287053,
 -0.027394265057703183,
 -0.10011206223842894,
 -0.0005842868538250149,
 -0.017793615845361842,

In [88]:
y_test

10941   -0.556999
5250     2.523704
10292   -1.254531
2266    -0.383694
6398    -1.006213
           ...   
4706     0.035343
8404     2.523704
11114   -0.386280
7877     1.322630
6188    -0.601834
Name: median_house_value, Length: 3400, dtype: float64

In [89]:
test_cost=cost_calculator(X_test, y_test, w, b)

In [90]:
test_cost

0.972313230461364

#### calculating the r2 score

In [86]:
from sklearn.metrics import r2_score

In [87]:
r2_score(predicted_value, y_test)

-20.039442801004263

In [98]:
regression_calculator(X_test.iloc[5].values, w, b)

AttributeError: ignored

In [97]:
X_test.iloc[5].values

array([ 0.7940264 , -0.91014163, -0.20572353, -0.471431  , -0.58699507,
       -0.63561748, -0.67676331,  0.85263957])