<a href="https://colab.research.google.com/github/haseeb-505/Python-Project-For-Data-Science/blob/main/assignment_1_question2_Housing_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**a): Write a function in Python that takes two vectors as input (weight and feature vector) and returns the linear regression prediction for that input.**

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import math

In [3]:
lr=LinearRegression()

In [4]:
def linear_regression_computer(x,w):
    """w: w is weight vector with values equal to 1. it is here user defined.. it can be calculated.\\
    x: x is feature vector;\\
    b: bias vector, and it can be added by user"""

#     b=np.array(x.shape) # since b and w are to be used in coming cells too, so we will define them globally
#     w=np.one(x.shape, float)
#     for i in range(len(x)):


    prediction=np.dot(x,w)
    return prediction



**b): Write a function in Python that takes a vector of predictions and a vector of actual values as
input and returns the Mean Squared Error.**

In [5]:
# from sklearn.metrics import mean_squared_error as mse


def mse_calculator(y_true, y_pred):
    """y_true: ture values\\
    y_pred: predicted values"""
    return sum((y_true-y_pred)**2)/len(y_true)

# y_test=[[2,4]]
# y_pred=lr.predict(w_test)

# mse_calculator(y_true=y_test, y_pred=y_pred)


**c): Write a function in Python that takes a vector of predictions and training data as input and
returns the Gradient of Mean Squared Error.**

In [6]:
def mse_gradient(x,y,w):
    """
    x: as of now, x is X_train.
    y: y is y_train
    """
    w_der=[]

    mse_grad=0

    for j in range(x.shape[0]):
#             mse=mse+(np.dot(x.iloc[j],w)-y.iloc[j])**2

        mse_grad=mse_grad+2*(np.dot((np.dot(x.iloc[j],w)-y.iloc[j]),x.iloc[j]))

    mse_grad/len(y)
    w_der.append(mse_grad)

    return w_der

**d): Write a function in Python that implements the gradient descent algorithm. The function
should take a weight vector, gradient of loss and a stopping criterion as input and return the
optimized weight vector.**

In [7]:


def grad_descent(x, y, initial_weight, step=0.1, iteration=10000):
    current_w=initial_weight
    print(current_w)

    w_update=[]
    loss=[]


    for i in range(iteration):
#         print(i)

        prediction=linear_regression_computer(X_train,w)
        mse=mse_calculator(y_train, prediction)
        w_der=mse_gradient(x,y,current_w)[0]

#         print(w_der)

#         print(current_w)

        current_w=current_w-(step*w_der)
#         print(current_w)
        w_update.append(current_w)
        loss.append(mse)


    return current_w

**e):  Use the functions created in the previous parts to apply linear regression on the California
Housing Dataset. You can You can find details about this dataset at the following link:
https://developers.google.com/machine-learning/crash-course/california-housing-datadescription**

In [8]:
url="https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv"

In [9]:
data=pd.read_csv(url)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


**There are no null/nan values in  the data. Moreover, all the data is of float type, i.e., continuous data. It is, in other terms, ready to use for linear regression.**

In [11]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

**Finding the correlation between the data and the median_house_value**

In [12]:
data.corrwith(data["median_house_value"])

longitude            -0.044982
latitude             -0.144917
housing_median_age    0.106758
total_rooms           0.130991
total_bedrooms        0.045783
population           -0.027850
households            0.061031
median_income         0.691871
median_house_value    1.000000
dtype: float64

In [13]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

**This shows that median_house_value is mostly depending on median_income.**

### Let's split the data into train, test set

In [14]:
### Scaling data

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc=StandardScaler()

In [17]:
sc.fit_transform(data)

array([[ 2.619365  , -0.67152023, -1.07967114, ..., -0.07599796,
        -1.25254316, -1.21055773],
       [ 2.53956878, -0.57326437, -0.76187201, ..., -0.09940441,
        -1.08148298, -1.09674535],
       [ 2.4946834 , -0.90546278, -0.92077158, ..., -0.99925206,
        -1.17010515, -1.04846131],
       ...,
       [-2.36291168,  2.90780067, -0.92077158, ..., -0.11760942,
        -0.44666313, -0.89412482],
       [-2.36291168,  2.88908527, -0.76187201, ..., -0.06039367,
        -0.99778717, -1.04759909],
       [-2.387848  ,  2.29955006,  1.85997083, ..., -0.60134255,
        -0.45536288, -0.97172417]])

In [18]:
data=pd.DataFrame(sc.fit_transform(data), columns=data.columns)

In [19]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   2.619365 -0.671520           -1.079671     1.361695        1.764204   
1   2.539569 -0.573264           -0.761872     2.296608        3.230441   
2   2.494683 -0.905463           -0.920772    -0.882462       -0.866956   
3   2.489696 -0.928857           -1.159121    -0.524186       -0.480230   
4   2.489696 -0.961609           -0.682422    -0.545747       -0.506328   

   population  households  median_income  median_house_value  
0   -0.361184   -0.075998      -1.252543           -1.210558  
1   -0.261865   -0.099404      -1.081483           -1.096745  
2   -0.955354   -0.999252      -1.170105           -1.048461  
3   -0.796793   -0.715774      -0.362600           -1.154514  
4   -0.701830   -0.622148      -1.026454           -1.222629

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test=train_test_split(data.drop(["median_house_value", "longitude", "latitude"],axis=1), data["median_house_value"], test_size=0.2, random_state=42)

In [22]:
X_train

housing_median_age  total_rooms  total_bedrooms  population  \
4679            -0.523523     0.030890       -0.444642   -0.108531   
2512            -1.318020     0.447426       -0.008092    0.066584   
993             -0.920772    -1.009075       -1.082858   -0.934445   
1327             0.429875    -0.169121       -0.390073   -0.355957   
4630             0.588774    -0.104898       -0.344995   -0.186941   
...                   ...          ...             ...         ...   
11284           -0.602972    -0.122788       -0.152818   -0.221789   
11964            0.986023    -0.857690       -0.938133   -0.935316   
5390             0.747674    -0.799430       -0.793407   -0.583344   
860             -1.556370     0.460729        0.843654    1.623449   
15795            1.859971    -0.087924        0.198320    0.437722   

       households  median_income  
4679    -0.346472       2.440711  
2512    -0.023984       1.738756  
993     -1.077274       0.662555  
1327    -0.317865      -0.129175  
4630    -0.229440       0.869043  
...           ...            ...  
11284   -0.156620      -0.147779  
11964   -0.913428      -0.168271  
5390    -0.762587      -0.481777  
860      0.881065      -0.411078  
15795    0.124257      -0.782599  

[13600 rows x 6 columns]

In [23]:
# since b and w are to be used in coming cells too, so we will define them globally
w=np.random.random(X_train.shape[1])

In [24]:
X_train.shape

(13600, 6)

In [25]:
X_train

housing_median_age  total_rooms  total_bedrooms  population  \
4679            -0.523523     0.030890       -0.444642   -0.108531   
2512            -1.318020     0.447426       -0.008092    0.066584   
993             -0.920772    -1.009075       -1.082858   -0.934445   
1327             0.429875    -0.169121       -0.390073   -0.355957   
4630             0.588774    -0.104898       -0.344995   -0.186941   
...                   ...          ...             ...         ...   
11284           -0.602972    -0.122788       -0.152818   -0.221789   
11964            0.986023    -0.857690       -0.938133   -0.935316   
5390             0.747674    -0.799430       -0.793407   -0.583344   
860             -1.556370     0.460729        0.843654    1.623449   
15795            1.859971    -0.087924        0.198320    0.437722   

       households  median_income  
4679    -0.346472       2.440711  
2512    -0.023984       1.738756  
993     -1.077274       0.662555  
1327    -0.317865      -0.129175  
4630    -0.229440       0.869043  
...           ...            ...  
11284   -0.156620      -0.147779  
11964   -0.913428      -0.168271  
5390    -0.762587      -0.481777  
860      0.881065      -0.411078  
15795    0.124257      -0.782599  

[13600 rows x 6 columns]

#### LinearRegression_Prediction

In [26]:

prediction=linear_regression_computer(X_train, w)
prediction

array([-0.09316514,  0.30410386, -2.43809837, ..., -1.55084378,
        1.58840142,  0.64227169])

In [27]:
y_test

10941   -0.556999
5250     2.523704
10292   -1.254531
2266    -0.383694
6398    -1.006213
           ...   
4706     0.035343
8404     2.523704
11114   -0.386280
7877     1.322630
6188    -0.601834
Name: median_house_value, Length: 3400, dtype: float64

#### MSE Calculator

In [28]:
mse_calculator(y_train, prediction)

4.966312328461131

#### Gradient of MSE

In [29]:
mse_gradient(X_train, y_train, w)[0]

array([-16201.75666589,  51908.33244372,  54216.52642891,  55297.77073077,
        54657.26739365, -10777.77212905])

#### Gradeient Descent

In [30]:
w

array([0.26220799, 0.73866639, 0.06361596, 0.52228306, 0.93896431,
       0.17682758])

In [31]:
%%time
grad_descent(X_train, y_train, initial_weight=w, iteration=25)

[0.26220799 0.73866639 0.06361596 0.52228306 0.93896431 0.17682758]
CPU times: user 56.8 s, sys: 5.28 s, total: 1min 2s
Wall time: 1min 2s


array([ 9.03273987e+099, -1.99211740e+100, -2.02571480e+100,
       -1.96518213e+100, -2.03041108e+100, -1.56510354e+099])

In [32]:
for i in X_train:
    print(i)


housing_median_age
total_rooms
total_bedrooms
population
households
median_income


In [33]:
X_train[i]

4679     2.440711
2512     1.738756
993      0.662555
1327    -0.129175
4630     0.869043
           ...   
11284   -0.147779
11964   -0.168271
5390    -0.481777
860     -0.411078
15795   -0.782599
Name: median_income, Length: 13600, dtype: float64

In [34]:
X_train.shape

(13600, 6)

In [35]:
X_train.iloc[1]

housing_median_age   -1.318020
total_rooms           0.447426
total_bedrooms       -0.008092
population            0.066584
households           -0.023984
median_income         1.738756
Name: 2512, dtype: float64

In [36]:
X_train.iloc[0]

housing_median_age   -0.523523
total_rooms           0.030890
total_bedrooms       -0.444642
population           -0.108531
households           -0.346472
median_income         2.440711
Name: 4679, dtype: float64

In [37]:
X_train.iloc[0].shape

(6,)

In [38]:
X_train.iloc[0][1]

0.030889542990726642

In [39]:
X_train.iloc[0][0]

-0.5235226619332849

In [40]:
def regression_calculator(x,w,b):
    pred=0
    f_wb=[]
    for i in range(x.shape[0]):

        pred=np.dot(x.iloc[i],w) + b

        f_wb.append(pred)

    return f_wb

In [41]:
### Initializing the weight vector
from numpy import random
random.seed(42)
w=np.random.rand(X_train.shape[1])
w

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452])

In [42]:
### setting the value of b, let it be 3
b=3

In [43]:
regression_calculator(X_train, w, b)

[2.769520100353915,
 3.2331543628265074,
 0.27901344911073345,
 2.4318483178163284,
 2.856113418671565,
 2.4334887016946443,
 2.0346227305272695,
 2.2341304302808767,
 3.065053284009497,
 1.5509306166429415,
 3.3802975620119025,
 2.1040130095281504,
 2.092094737279288,
 0.8077543770166189,
 1.3971882181791657,
 1.5370210324995797,
 1.4383997237504018,
 3.700113713050869,
 1.545849987024242,
 1.7673557571755347,
 2.205444256208743,
 2.1355015502721875,
 2.8376588090805743,
 1.4472412806433723,
 1.8086319919296208,
 3.3065054564535927,
 2.679989948133433,
 2.8265364666477035,
 0.8520993547109548,
 3.059601798177085,
 1.6342543148627062,
 2.914462405398515,
 2.375829863923027,
 1.3474368340670868,
 4.683944221879436,
 1.0974511334973438,
 3.465788780673709,
 3.271842993025036,
 1.8906954774829328,
 2.0848087961160546,
 1.3906710638877924,
 4.78551696592401,
 1.3898857790981745,
 2.8269105551713345,
 -0.21425264643451536,
 2.1663976650914467,
 0.8159179089976956,
 9.22377891310558,
 0.6106

In [44]:
len(regression_calculator(X_train, w, b))

13600

In [45]:
y_train.shape

(13600,)

In [46]:
y_train

4679     1.651134
2512     1.261413
993     -0.589763
1327    -0.267295
4630     1.024304
           ...   
11284   -0.626838
11964   -0.793246
5390    -0.516475
860     -0.557861
15795    0.248310
Name: median_house_value, Length: 13600, dtype: float64

In [47]:
def cost_calculator(x,y,w,b):

    cost=0

    for i in range(x.shape[0]):

        f_wb=np.dot(x.iloc[i],w) + b

#         cost calculator
        cost+=(f_wb-y.iloc[i])**2

#     dividing by number of events, as it is in mean squared error formula
    cost=cost/x.shape[0]

    return cost

In [48]:
cost_calculator(X_train, y_train, w, b)

14.56880314500366

In [49]:
def gradient_calculator(x,y,w,b):

    dw=0
    db=0

    for i in range(x.shape[0]):

        f_wb=np.dot(x.iloc[i],w)+b

#       differential of cost w.r.t w and we will divide the sum later on by x.shape[0]
        dw_i=sum((np.dot(X_train.iloc[i],w)+b-y_train.iloc[i])*X_train.iloc[i])
#       sum of differentials
        dw+=dw_i
#     differential of cost w.r.t bias and we will divide the sum later on by x.shape[0]
        db_i=(f_wb-y.iloc[i])
#     sum of bias differential
        db+=db_i
#     division by x.shape[0]
    dw=dw/x.shape[0]
    db=db/x.shape[0]

    return dw, db


In [50]:
dw,db=gradient_calculator(X_train,y_train,w,b)

In [51]:
dw

7.451992413772107

In [52]:
db

3.005742826964554

### updating weights and bias using batch gradient descent

In [53]:
def gradient_updation(x,y,w,b, cost_function=cost_calculator,
                      gradient_function=gradient_calculator,  iterations=100000, alpha=0.1):

    cost_history=[]
    w_history=[]

    for i in range(iterations):
        dw, db=gradient_function(x,y,w,b)
#       updating the parameters
        w=w-alpha*dw

        b=b-alpha*db

#       saving the cost for each iteration
        if i<100000:
            cost=cost_function(x,y,w,b)
            cost_history.append(cost)
        # Print cost every at intervals 20 times or as many iterations if < 20
        if i% math.ceil(iterations/100)==0:
            w_history.append(w)
            print(f"Iteration {i:4}: Cost {float(cost_history[-1]):8.5f}   ")

    return w,b, cost_history, w_history

In [54]:
w=np.array([0,0,0,0,0,0])
b=0

In [55]:
%%time
w,b,cost_history,w_history = gradient_updation(X_train, y_train, w, b, iterations=20)

Iteration    0: Cost  0.93944   
Iteration    1: Cost  0.92845   
Iteration    2: Cost  0.92623   
Iteration    3: Cost  0.92578   
Iteration    4: Cost  0.92569   
Iteration    5: Cost  0.92567   
Iteration    6: Cost  0.92567   
Iteration    7: Cost  0.92566   
Iteration    8: Cost  0.92566   
Iteration    9: Cost  0.92566   
Iteration   10: Cost  0.92566   
Iteration   11: Cost  0.92566   
Iteration   12: Cost  0.92566   
Iteration   13: Cost  0.92566   
Iteration   14: Cost  0.92566   
Iteration   15: Cost  0.92566   
Iteration   16: Cost  0.92566   
Iteration   17: Cost  0.92566   
Iteration   18: Cost  0.92566   
Iteration   19: Cost  0.92566   
CPU times: user 1min 55s, sys: 5.35 s, total: 2min
Wall time: 1min 58s


In [56]:
w

array([0.06855893, 0.06855893, 0.06855893, 0.06855893, 0.06855893,
       0.06855893])

In [57]:
b

-0.004521850590506979

In [58]:
w_history

[array([0.09936807, 0.09936807, 0.09936807, 0.09936807, 0.09936807,
        0.09936807]),
 array([0.05471356, 0.05471356, 0.05471356, 0.05471356, 0.05471356,
        0.05471356]),
 array([0.07478066, 0.07478066, 0.07478066, 0.07478066, 0.07478066,
        0.07478066]),
 array([0.06576283, 0.06576283, 0.06576283, 0.06576283, 0.06576283,
        0.06576283]),
 array([0.06981533, 0.06981533, 0.06981533, 0.06981533, 0.06981533,
        0.06981533]),
 array([0.06799421, 0.06799421, 0.06799421, 0.06799421, 0.06799421,
        0.06799421]),
 array([0.06881261, 0.06881261, 0.06881261, 0.06881261, 0.06881261,
        0.06881261]),
 array([0.06844484, 0.06844484, 0.06844484, 0.06844484, 0.06844484,
        0.06844484]),
 array([0.06861012, 0.06861012, 0.06861012, 0.06861012, 0.06861012,
        0.06861012]),
 array([0.06853586, 0.06853586, 0.06853586, 0.06853586, 0.06853586,
        0.06853586]),
 array([0.06856924, 0.06856924, 0.06856924, 0.06856924, 0.06856924,
        0.06856924]),
 array([0.

In [59]:
cost_history

[0.9394376466076537,
 0.9284541553599602,
 0.9262335894467788,
 0.9257831419069004,
 0.9256905465679169,
 0.9256705278875944,
 0.9256654165196464,
 0.9256635186835109,
 0.9256624342765717,
 0.92566164735671,
 0.9256610284196168,
 0.9256605308101328,
 0.9256601284996308,
 0.925659802780208,
 0.9256595389781986,
 0.9256593253047783,
 0.925659152230551,
 0.925659012040684,
 0.9256588984869414,
 0.9256588065084186]

### Using the updated w and b to make prediction on test data

In [60]:
predicted_value=regression_calculator(X_test, w, b)

In [61]:
predicted_value

[0.14610971591931626,
 0.2268624371301873,
 0.04070506205313429,
 0.203753062970497,
 -0.0761012111321782,
 -0.12270995198937468,
 -0.2337760950116808,
 -0.3069227614838517,
 -0.02669974835016859,
 0.05658148454480497,
 -0.2719330292257469,
 -0.08173917728044934,
 -0.009482195470366448,
 -0.14743918474738987,
 0.06189860492466836,
 -0.18889176195556123,
 -0.08594416586005811,
 -0.39820390804683947,
 -0.33582548766274406,
 0.0773155755218337,
 -0.2127778055987513,
 -0.3029162141136014,
 -0.10241543208223262,
 0.27320556711337013,
 0.1741226581225498,
 -0.10000406357627116,
 -0.11257142452179676,
 -0.06858266542048856,
 -0.1514951461568189,
 -0.31528021150525626,
 -0.129577829242328,
 -0.15632257392613835,
 -0.17138068158837022,
 -0.15396472416172766,
 -0.06294864956472081,
 -0.0023642548505684816,
 -0.2610988466002776,
 0.10727627059675655,
 -0.24286809561211814,
 -0.029107150485090175,
 -0.015081229587284578,
 -0.08753153788392393,
 0.0060106990013840175,
 -0.013877239163960551,
 0.018

In [62]:
y_test

10941   -0.556999
5250     2.523704
10292   -1.254531
2266    -0.383694
6398    -1.006213
           ...   
4706     0.035343
8404     2.523704
11114   -0.386280
7877     1.322630
6188    -0.601834
Name: median_house_value, Length: 3400, dtype: float64

In [63]:
test_cost=cost_calculator(X_test, y_test, w, b)

In [64]:
test_cost

0.9477926689257857

#### calculating the r2 score

In [65]:
from sklearn.metrics import r2_score

In [70]:
r2_score(y_test, predicted_value)

0.07472829250530677

In [67]:
y5_predicted=sum(X_test.iloc[5].values*w+b)

In [68]:
y5_predicted

-0.14531920494190956

In [69]:
y_test.iloc[5]

0.21382145333183344

In [72]:
from sklearn.linear_model import LinearRegression

In [73]:
lr=LinearRegression()

In [74]:
lr.fit(X_train, y_train)

LinearRegression()

In [75]:
pred=lr.predict(X_test)
pred

array([-0.3310093 ,  1.97642378, -0.8574936 , ..., -1.61587612,
        0.68946683, -1.04410505])

In [76]:
y_test

10941   -0.556999
5250     2.523704
10292   -1.254531
2266    -0.383694
6398    -1.006213
           ...   
4706     0.035343
8404     2.523704
11114   -0.386280
7877     1.322630
6188    -0.601834
Name: median_house_value, Length: 3400, dtype: float64

In [77]:
from sklearn.metrics import mean_squared_error as mse

In [78]:
mse(y_test, lr.predict(X_test))

0.41324969464453515

In [79]:
r2_score(y_test, lr.predict(X_test))

0.5965697318393681